const trait_options = [
    "Abstract",
    "Adventure",
    "Advertising",
    "Architecture",
    "Astrophotography",
    "Black & White",
    "Boudoir",
    "Candid",
    "City",
    "Commercial",
    "Crystal Ball",
    "Documentary",
    "Drone",
    "Editorial",
    "Event",
    "Family",
    "Fashion",
    "Fine Art",
    "Fish-eye",
    "Food",
    "Forced Perspective",
    "Glamour",
    "Golden Hour",
    "Head Shot",
    "High Dynamic Range",
    "Indoor",
    "Infrared",
    "Kinetic",
    "Landscape",
    "Lifestyle",
    "Long Exposure",
    "Macro",
    "Milky Way",
    "Minimalist",
    "Mobile",
    "Multiple Exposure",
    "Newborn",
    "Night",
    "Panorama",
    "Pet",
    "Photojournalism",
    "Portrait",
    "Prism",
    "Product",
    "Real Estate",
    "Scientific",
    "Seascape",
    "Social Media",
    "Sports",
    "Still-life",
    "Stock",
    "Street",
    "Tilt-Shift",
    "Time-Lapse",
    "Travel",
    "Urban Exploration",
    "War",
    "Wedding",
    "Wildlife"
  ]

export default trait_options;